/**
 * The connector store: every app a person can connect, import from, or reach
 * through a remote MCP server. Hub web renders this list; hub-api adds each
 * person's connection status (GET /api/connectors/catalog).
 *
 * Names and logos belong to their owners; they are shown only to identify the
 * service being connected.
 */

export type ConnectorCategory =
  | "suites"
  | "mail_calendar"
  | "files_docs"
  | "work_tracking"
  | "notes_docs"
  | "meetings"
  | "chat"
  | "developer"
  | "design"
  | "sales_support"
  | "analytics"
  | "finance"
  | "recruiting"
  | "sign"
  | "cloud";

export const CONNECTOR_CATEGORIES: ReadonlyArray<{ id: ConnectorCategory; label: string }> = [
  { id: "suites", label: "Google & Microsoft" },
  { id: "mail_calendar", label: "Mail & calendar" },
  { id: "files_docs", label: "Files & docs" },
  { id: "work_tracking", label: "Projects & issues" },
  { id: "notes_docs", label: "Notes & wikis" },
  { id: "meetings", label: "Meetings" },
  { id: "chat", label: "Chat" },
  { id: "developer", label: "Developer" },
  { id: "design", label: "Design" },
  { id: "sales_support", label: "Sales & support" },
  { id: "analytics", label: "Analytics" },
  { id: "finance", label: "Finance" },
  { id: "recruiting", label: "Recruiting" },
  { id: "sign", label: "Signatures" },
  { id: "cloud", label: "Cloud" },
];

/**
 * How the connection is made.
 * - oauth: Ensemble's own OAuth app for the provider (the operator registers it once).
 * - token: the person pastes a personal token.
 * - mcp: the vendor's hosted MCP server, OAuth with dynamic client registration; no operator setup.
 * - file: an export file is uploaded (imports only).
 * - builtin: always on.
 */
export type ConnectorAuthKind = "oauth" | "token" | "mcp" | "file" | "builtin";

/** Products inside a suite. Each can be switched on or off; OAuth asks only for the scopes of the ones that are on. */
export interface ConnectorProduct {
  id: string;
  name: string;
  /** Plain-language access, e.g. "Read your mail" or "Create and edit documents". */
  access: string;
  /** Sync sources this product feeds (settings.connections keys). */
  sources?: readonly string[];
  write: boolean;
  defaultOn: boolean;
}

export interface ConnectorImport {
  /** Import source id understood by POST /api/imports. */
  source: string;
  /** Uploaded export formats the importer reads, e.g. ["csv", "zip"]. */
  files?: readonly string[];
  /** True when the importer can pull through the connected account or a pasted token. */
  api: boolean;
  /** Where to create a personal token, for the token path. */
  tokenUrl?: string;
  tokenHint?: string;
  /** What comes across, e.g. ["Databases as projects", "Rows as tasks with due dates and tags", "Pages"]. */
  brings: readonly string[];
}

export interface ConnectorCatalogEntry {
  id: string;
  name: string;
  vendor: string;
  category: ConnectorCategory;
  /** Shown in the short Connections list in Settings; everything else lives in Browse connectors. */
  featured: boolean;
  /** Logo key for components/connectors/brand-logo.tsx. */
  logo: string;
  tagline: string;
  /** How it connects. A connector can offer more than one, e.g. Linear: token sync plus MCP tools plus import. */
  auth: readonly ConnectorAuthKind[];
  /** oauth_tokens provider for oauth/token connectors. */
  provider?: string;
  products?: readonly ConnectorProduct[];
  /** Things it reads, in plain words. */
  reads: readonly string[];
  /** Things it can change. Every change waits for Apply. */
  writes: readonly string[];
  /** Remote MCP server, for auth "mcp". */
  mcp?: { url: string; transport: "streamable-http" | "sse"; docs?: string; note?: string };
  import?: ConnectorImport;
  /** ready: works today. setup: needs the operator's app keys (see private setup docs). soon: listed, not built. */
  status: "ready" | "soon";
  /** Shown on the detail view: plan requirements, account types, review notes. */
  notes?: readonly string[];
  docsUrl?: string;
}

const MCP = (url: string, note?: string): ConnectorCatalogEntry["mcp"] => ({ url, transport: "streamable-http", ...(note ? { note } : {}) });


const mcpApp = (
  id: string,
  name: string,
  vendor: string,
  category: ConnectorCategory,
  url: string,
  tagline: string,
  reads: readonly string[],
  writes: readonly string[],
  notes?: readonly string[],
  logo: string = id,
): ConnectorCatalogEntry => ({
  id,
  name,
  vendor,
  category,
  featured: false,
  logo,
  tagline,
  auth: ["mcp"],
  reads,
  writes,
  mcp: MCP(url),
  status: "ready",
  ...(notes ? { notes } : {}),
});

/** Popular apps with an official remote MCP server that registers clients on its own (checked 7 Oct 2026). */
const MORE_MCP_APPS: readonly ConnectorCatalogEntry[] = [
  mcpApp("calendly", "Calendly", "Calendly", "mail_calendar", "https://mcp.calendly.com", "Event types, bookings and availability.", ["Scheduled events and invitees"], ["Scheduling links and event changes"]),
  mcpApp("caldotcom", "Cal.com", "Cal.com", "mail_calendar", "https://mcp.cal.com/mcp", "Bookings, event types and availability.", ["Bookings and schedules"], ["Bookings"]),
  mcpApp("evernote", "Evernote", "Bending Spoons", "notes_docs", "https://mcp.evernote.com/mcp", "Search and read your notes and notebooks.", ["Notes and notebooks"], ["Notes"], ["Evernote's MCP server is a beta for paid plans."]),
  mcpApp("readwise", "Readwise", "Readwise", "notes_docs", "https://mcp2.readwise.io/mcp", "Highlights and saved articles from Readwise and Reader.", ["Highlights and documents"], [], ["Needs a Readwise subscription."]),
  mcpApp("guru", "Guru", "Guru", "notes_docs", "https://mcp.api.getguru.com/mcp", "Your team's verified knowledge cards.", ["Cards and collections"], [], ["Needs a paid Guru plan."]),
  mcpApp("gamma", "Gamma", "Gamma", "design", "https://mcp.gamma.app/mcp", "Turn notes into presentations, documents and pages.", ["Your Gamma creations"], ["New presentations and documents"]),
  mcpApp("pitch", "Pitch", "Pitch", "design", "https://mcp.pitch.com/mcp", "Presentations in your Pitch workspace.", ["Presentations"], ["Presentations"]),
  mcpApp("pipedrive", "Pipedrive", "Pipedrive", "sales_support", "https://mcp.pipedrive.ai/mcp", "Deals, contacts and activities.", ["Deals, people, organizations and activities"], ["Deals and activities"]),
  mcpApp("attio", "Attio", "Attio", "sales_support", "https://mcp.attio.com/mcp", "CRM records, lists and notes.", ["Records, lists and notes"], ["Records and notes"], ["Included on Attio's free plan."]),
  mcpApp("close", "Close", "Close", "sales_support", "https://mcp.close.com/mcp", "Leads, opportunities and activity.", ["Leads, contacts and opportunities"], ["Leads and tasks"]),
  mcpApp("customerio", "Customer.io", "Customer.io", "sales_support", "https://mcp.customer.io/mcp", "Campaigns, segments and customer profiles.", ["Campaigns and people"], [], ["Needs a paid Customer.io plan."]),
  mcpApp("whatsapp", "WhatsApp Business", "Meta", "chat", "https://mcp.facebook.com/whatsapp_business_tools", "Business messaging templates and conversations.", ["Templates and business account details"], ["Messages, billed by Meta per conversation"], ["Sending needs a verified Meta business account."]),
  mcpApp("posthog", "PostHog", "PostHog", "analytics", "https://mcp.posthog.com", "Product analytics, feature flags and errors.", ["Insights, events, flags and errors"], ["Feature flags and annotations"]),
  mcpApp("mixpanel", "Mixpanel", "Mixpanel", "analytics", "https://mcp.mixpanel.com/mcp", "Ask questions about your product analytics.", ["Events, reports and cohorts"], []),
  mcpApp("amplitude", "Amplitude", "Amplitude", "analytics", "https://mcp.amplitude.com/mcp", "Charts, dashboards and user behaviour.", ["Charts, cohorts and events"], []),
  mcpApp("quickbooks", "QuickBooks", "Intuit", "finance", "https://mcp.quickbooks.intuit.com", "Invoices, customers and reports.", ["Invoices, bills, customers and reports"], ["Invoices and customers"], ["Needs a paid QuickBooks Online company."]),
  mcpApp("paypal", "PayPal", "PayPal", "finance", "https://mcp.paypal.com", "Invoices, orders and transactions.", ["Transactions, invoices and disputes"], ["Invoices"]),
  mcpApp("greenhouse", "Greenhouse", "Greenhouse", "recruiting", "https://mcp.greenhouse.io/mcp", "Candidates, jobs and interviews.", ["Candidates, applications and jobs"], ["Notes and stages"], ["Needs a Greenhouse Recruiting account."]),
  mcpApp("ashby", "Ashby", "Ashby", "recruiting", "https://mcp.ashbyhq.com/mcp/v1", "Candidates, jobs and interview plans.", ["Candidates, jobs and applications"], ["Notes and stages"], ["Needs an Ashby account."]),
];

const MORE_SOON: readonly ConnectorCatalogEntry[] = [
  { id: "salesforce", name: "Salesforce", vendor: "Salesforce", category: "sales_support", featured: false, logo: "salesforce", tagline: "Accounts, opportunities and cases.", auth: ["oauth"], reads: ["CRM records"], writes: [], status: "soon", notes: ["Each Salesforce org has its own MCP address and needs an app registered by its admin."] },
  { id: "zendesk", name: "Zendesk", vendor: "Zendesk", category: "sales_support", featured: false, logo: "zendesk", tagline: "Tickets and help-centre articles.", auth: ["token"], reads: ["Tickets"], writes: [], status: "soon" },
  { id: "front", name: "Front", vendor: "Front", category: "sales_support", featured: false, logo: "front", tagline: "Shared inbox conversations.", auth: ["oauth"], reads: ["Conversations"], writes: [], status: "soon", notes: ["Front's MCP server needs an app registered with Front."] },
  { id: "discord", name: "Discord", vendor: "Discord", category: "chat", featured: false, logo: "discord", tagline: "Server channels you choose.", auth: ["token"], reads: ["Channel messages"], writes: [], status: "soon" },
  { id: "xero", name: "Xero", vendor: "Xero", category: "finance", featured: false, logo: "xero", tagline: "Invoices, bills and contacts.", auth: ["oauth"], reads: ["Accounting records"], writes: [], status: "soon" },
];

export const CONNECTOR_CATALOG: readonly ConnectorCatalogEntry[] = [
  {
    id: "google_workspace",
    name: "Google Workspace",
    vendor: "Google",
    category: "suites",
    featured: true,
    logo: "google",
    tagline: "Gmail, Calendar, Drive, Docs, Sheets and Slides with one sign-in.",
    auth: ["oauth"],
    provider: "google",
    products: [
      { id: "gmail", name: "Gmail", access: "Read mail you are on", sources: ["gmail"], write: false, defaultOn: true },
      { id: "calendar", name: "Google Calendar", access: "Read events, create events and send invites", sources: ["google_calendar"], write: true, defaultOn: true },
      { id: "drive_docs", name: "Drive, Docs, Sheets and Slides", access: "Create and edit documents, and open files you pick", write: true, defaultOn: true },
      { id: "drive_search", name: "Search all of Drive", access: "Read any file in your Drive", write: false, defaultOn: false },
    ],
    reads: ["Mail threads you are on", "Calendar events", "Drive files you pick or Ensemble created"],
    writes: ["Calendar events and invites", "Docs, Sheets and Slides"],

    status: "ready",
    notes: [
      "Gmail and Search all of Drive are restricted Google permissions. Until Google reviews this server, at most 100 people can approve them.",
      "Docs, Sheets and Slides only touch files Ensemble created or files you choose.",
    ],
  },
  {
    id: "microsoft_365",
    name: "Microsoft 365",
    vendor: "Microsoft",
    category: "suites",
    featured: true,
    logo: "microsoft",
    tagline: "Outlook mail and calendar, Teams, OneDrive, Word, Excel and PowerPoint.",
    auth: ["oauth"],
    provider: "microsoft",
    products: [
      { id: "outlook_mail", name: "Outlook mail", access: "Read mail", sources: ["outlook"], write: false, defaultOn: true },
      { id: "outlook_calendar", name: "Outlook calendar", access: "Read events, create events and send invites", sources: ["outlook_calendar"], write: true, defaultOn: true },
      { id: "teams", name: "Teams chats", access: "Read your chats (work or school accounts)", sources: ["teams"], write: false, defaultOn: false },
      { id: "onedrive", name: "OneDrive", access: "Read your files", write: false, defaultOn: true },
      { id: "office", name: "Word, Excel and PowerPoint", access: "Create and edit Office files in OneDrive", write: true, defaultOn: true },
    ],
    reads: ["Outlook mail", "Outlook calendar", "Teams chats", "OneDrive files"],
    writes: ["Outlook events and invites", "Word, Excel and PowerPoint files"],
    status: "ready",
    notes: [
      "Teams chats need a work or school account; personal Microsoft accounts have no Teams chat API.",
      "Some organizations require an admin to approve new apps before you can connect.",
    ],
  },
  {
    id: "notion",
    name: "Notion",
    vendor: "Notion Labs",
    category: "notes_docs",
    featured: true,
    logo: "notion",
    tagline: "Search, read and update pages and databases. Import your workspace.",
    auth: ["mcp", "oauth", "token"],
    provider: "notion",
    reads: ["Pages and databases you share"],
    writes: ["Pages, database rows and comments"],
    mcp: MCP("https://mcp.notion.com/mcp"),
    import: {
      source: "notion",
      files: ["zip", "csv"],
      api: true,
      tokenUrl: "https://www.notion.so/profile/integrations",
      tokenHint: "Create an internal integration, copy its secret, then share the pages to import with it (••• → Connections).",
      brings: ["Databases as projects", "Rows as tasks with dates, status, tags and people", "Pages with their content"],
    },
    status: "ready",
  },
  {
    id: "linear",
    name: "Linear",
    vendor: "Linear",
    category: "work_tracking",
    featured: true,
    logo: "linear",
    tagline: "Your issues as proposed todos, plus issue tools and a full import.",
    auth: ["token", "oauth", "mcp"],
    provider: "linear",
    reads: ["Issues assigned to you", "Teams, projects and cycles"],
    writes: ["Issues, comments and projects"],
    mcp: MCP("https://mcp.linear.app/mcp"),
    import: {
      source: "linear",
      files: ["csv"],
      api: true,
      tokenUrl: "https://linear.app/settings/account/security",
      tokenHint: "Settings → Security & access → Personal API keys → New key.",
      brings: ["Projects", "Issues with status, priority, labels, due dates and assignees", "Descriptions as pages"],
    },
    status: "ready",
  },
  {
    id: "github",
    name: "GitHub",
    vendor: "GitHub",
    category: "developer",
    featured: true,
    logo: "github",
    tagline: "Pull requests, reviews and issues; import issues as tasks.",
    auth: ["oauth", "token"],
    provider: "github",
    reads: ["Your open PRs, review requests and assigned issues"],
    writes: [],
    import: {
      source: "github",
      api: true,
      tokenUrl: "https://github.com/settings/personal-access-tokens/new",
      tokenHint: "A fine-grained token with read access to Issues on the repositories to import.",
      brings: ["Issues with labels, milestones as due dates, and state"],
    },
    status: "ready",
  },
  {
    id: "slack",
    name: "Slack",
    vendor: "Slack",
    category: "chat",
    featured: false,
    logo: "slack",
    tagline: "DMs, group DMs and channels you choose; direct asks become proposed todos.",
    auth: ["token", "oauth"],
    provider: "slack",
    reads: ["DMs, group DMs and listed channels"],
    writes: [],
    status: "ready",
  },
  {
    id: "atlassian",
    name: "Jira & Confluence",
    vendor: "Atlassian",
    category: "work_tracking",
    featured: false,
    logo: "jira",
    tagline: "Import Jira issues with labels, due dates and status; Jira and Confluence tools when your admin allows.",
    auth: ["oauth", "token", "mcp"],
    provider: "atlassian",
    reads: ["Jira issues and projects", "Confluence pages (through Atlassian's MCP server)"],
    writes: ["Jira issues and Confluence pages (through Atlassian's MCP server)"],
    mcp: MCP("https://mcp.atlassian.com/v2/mcp", "Your Atlassian site admin may need to add api.ensemblework.com to the allowed domains for the Rovo MCP server."),
    import: {
      source: "jira",
      files: ["csv"],
      api: true,
      tokenUrl: "https://id.atlassian.com/manage-profile/security/api-tokens",
      tokenHint: "Create an API token, then enter your Atlassian email and site (yourteam.atlassian.net).",
      brings: ["Projects", "Issues with status, priority, labels, due dates, assignees and epics", "Descriptions as pages"],
    },
    status: "ready",
  },
  {
    id: "trello",
    name: "Trello",
    vendor: "Atlassian",
    category: "work_tracking",
    featured: false,
    logo: "trello",
    tagline: "Bring boards, lists and cards across with due dates, labels and checklists.",
    auth: ["token", "file"],
    provider: "trello",
    reads: ["Boards, lists and cards"],
    writes: [],
    import: {
      source: "trello",
      files: ["json"],
      api: true,
      tokenUrl: "https://trello.com/power-ups/admin",
      tokenHint: "Easiest: board menu → Print, export and share → Export as JSON, then upload the file.",
      brings: ["Boards as projects", "Cards as tasks with due dates, labels and members", "Checklists in the task page"],
    },
    status: "ready",
  },
  {
    id: "asana",
    name: "Asana",
    vendor: "Asana",
    category: "work_tracking",
    featured: false,
    logo: "asana",
    tagline: "Import Asana projects and tasks with due dates, tags and assignees.",
    auth: ["token", "file"],
    provider: "asana",
    reads: ["Projects and tasks"],
    writes: [],
    notes: ["Asana's MCP server needs an app registered with Asana, so assistant tools for Asana come later."],
    import: {
      source: "asana",
      files: ["csv"],
      api: true,
      tokenUrl: "https://app.asana.com/0/my-apps",
      tokenHint: "My apps → Create new token.",
      brings: ["Projects", "Tasks with due dates, tags, assignees and notes"],
    },
    status: "ready",
  },
  {
    id: "todoist",
    name: "Todoist",
    vendor: "Doist",
    category: "work_tracking",
    featured: false,
    logo: "todoist",
    tagline: "Todoist tools in the assistant, and an import of projects, tasks and labels.",
    auth: ["mcp", "token", "file"],
    provider: "todoist",
    reads: ["Projects and tasks"],
    writes: ["Tasks and projects"],
    mcp: MCP("https://ai.todoist.net/mcp"),
    import: {
      source: "todoist",
      files: ["csv"],
      api: true,
      tokenUrl: "https://app.todoist.com/app/settings/integrations/developer",
      tokenHint: "Settings → Integrations → Developer → API token.",
      brings: ["Projects", "Tasks with due dates, priorities, labels and descriptions"],
    },
    status: "ready",
  },
  {
    id: "clickup",
    name: "ClickUp",
    vendor: "ClickUp",
    category: "work_tracking",
    featured: false,
    logo: "clickup",
    tagline: "ClickUp tools in the assistant, and a list and task import.",
    auth: ["mcp", "token", "file"],
    provider: "clickup",
    reads: ["Spaces, lists, tasks and docs"],
    writes: ["Tasks, lists and docs"],
    mcp: MCP("https://mcp.clickup.com/mcp"),
    import: {
      source: "clickup",
      files: ["csv"],
      api: true,
      tokenUrl: "https://app.clickup.com/settings/apps",
      tokenHint: "Settings → Apps → API Token → Generate.",
      brings: ["Lists as projects", "Tasks with status, priority, tags, due dates and assignees"],
    },
    status: "ready",
  },
  {
    id: "monday",
    name: "monday.com",
    vendor: "monday.com",
    category: "work_tracking",
    featured: false,
    logo: "monday",
    tagline: "monday.com tools in the assistant, and a board import.",
    auth: ["mcp", "token"],
    provider: "monday",
    reads: ["Boards and items"],
    writes: ["Items and updates"],
    mcp: MCP("https://mcp.monday.com/mcp"),
    import: {
      source: "monday",
      api: true,
      tokenUrl: "https://auth.monday.com/users/sign_in",
      tokenHint: "Profile picture → Developers → My access tokens → Show.",
      brings: ["Boards as projects", "Items as tasks with status, dates, tags and people"],
    },
    status: "ready",
  },
  {
    id: "airtable",
    name: "Airtable",
    vendor: "Airtable",
    category: "work_tracking",
    featured: false,
    logo: "airtable",
    tagline: "Read and update bases, tables and records from the assistant.",
    auth: ["mcp"],
    reads: ["Bases, tables and records"],
    writes: ["Records and comments"],
    mcp: MCP("https://mcp.airtable.com/mcp"),
    status: "ready",
  },
  {
    id: "granola",
    name: "Granola",
    vendor: "Granola",
    category: "meetings",
    featured: false,
    logo: "granola",
    tagline: "Your meeting notes and transcripts, ready to turn into tasks.",
    auth: ["mcp", "token"],
    provider: "granola",
    reads: ["Meeting notes and transcripts", "AI summaries, matched to your calendar"],
    writes: [],
    mcp: MCP("https://mcp.granola.ai/mcp", "On Granola's free plan only the last 30 days of notes are available."),
    status: "ready",
    notes: [
      "The MCP connection works on any plan; syncing notes into Meeting notes needs a Granola API key (Business plan or above).",
      "Create the key in the Granola app → Settings → Connectors → API keys.",
    ],
    docsUrl: "https://docs.granola.ai/introduction",
  },
  {
    id: "zoom",
    name: "Zoom",
    vendor: "Zoom",
    category: "meetings",
    featured: false,
    logo: "zoom",
    tagline: "Upcoming meetings, recordings and transcripts.",
    auth: ["oauth"],
    provider: "zoom",
    reads: ["Meetings, cloud recordings and transcripts"],
    writes: [],
    status: "ready",
    notes: ["Cloud recordings and transcripts need a paid Zoom plan."],
  },
  // Meeting-notes tools. "token" entries sync transcripts into Meeting notes (hub-api connectors/meetings);
  // "mcp" lets the assistant ask them live.
  {
    id: "fireflies",
    name: "Fireflies.ai",
    vendor: "Fireflies.ai",
    category: "meetings",
    featured: false,
    logo: "fireflies",
    tagline: "Transcripts, summaries and action items from the meetings Fred records.",
    auth: ["token", "mcp"],
    provider: "fireflies",
    reads: ["Meeting transcripts with speakers", "Summaries and action items", "Attendees"],
    writes: [],
    mcp: MCP("https://api.fireflies.ai/mcp"),
    status: "ready",
    notes: [
      "Create an API key at app.fireflies.ai → Integrations → Fireflies API (https://app.fireflies.ai/integrations/custom/fireflies).",
      "The free plan's API allowance is small (about 50 requests a day); each Sync now uses one or two.",
    ],
    docsUrl: "https://docs.fireflies.ai/",
  },
  {
    id: "fathom",
    name: "Fathom",
    vendor: "Fathom",
    category: "meetings",
    featured: false,
    logo: "fathom",
    tagline: "Recorded meetings with transcript, summary and assigned action items.",
    auth: ["token", "mcp"],
    provider: "fathom",
    reads: ["Meetings you recorded or that were shared with you", "Transcripts, summaries and action items"],
    writes: [],
    mcp: MCP("https://api.fathom.ai/mcp"),
    status: "ready",
    notes: [
      "Create an API key in Fathom → Settings → API Access (https://fathom.video/customize#api-access-header). The free plan includes one.",
      "A key sees only meetings you recorded or that were shared with you or your team.",
    ],
    docsUrl: "https://developers.fathom.ai/quickstart",
  },
  {
    id: "tldv",
    name: "tl;dv",
    vendor: "tl;dv",
    category: "meetings",
    featured: false,
    logo: "tldv",
    tagline: "Meeting recordings, transcripts and AI notes.",
    auth: ["token"],
    provider: "tldv",
    reads: ["Meetings, transcripts and notes"],
    writes: [],
    status: "ready",
    notes: [
      "Create an API key at https://tldv.io/app/settings/personal-settings/api-keys.",
      "API access depends on the meeting organiser's plan: Pro, Business or Enterprise. Free-plan meetings are not returned.",
    ],
    docsUrl: "https://doc.tldv.io/",
  },
  {
    id: "krisp",
    name: "Krisp",
    vendor: "Krisp",
    category: "meetings",
    featured: false,
    logo: "krisp",
    tagline: "Meeting transcripts, AI notes and action items.",
    auth: ["token", "mcp"],
    provider: "krisp",
    reads: ["Meetings you own or that were shared with you", "Transcripts, notes and action items"],
    writes: [],
    mcp: MCP("https://mcp.krisp.ai/mcp"),
    status: "ready",
    notes: ["Create a Read key in Krisp → Integrations → API. Personal API keys need the Core or Advanced plan."],
    docsUrl: "https://meeting-api-docs.krisp.ai/docs/getting-started",
  },
  {
    id: "jamie",
    name: "Jamie",
    vendor: "Jamie",
    category: "meetings",
    featured: false,
    logo: "jamie",
    tagline: "Bot-free meeting notes with summaries and tasks.",
    auth: ["token", "mcp"],
    provider: "jamie",
    reads: ["Your meetings and meetings shared with you", "Summaries, transcripts and tasks"],
    writes: [],
    mcp: MCP("https://mcp.meetjamie.ai/mcp"),
    status: "ready",
    notes: ["Create a personal key (jk_…) in Jamie → Settings → Developers → API Keys. Needs the Pro, Team or Enterprise plan."],
    docsUrl: "https://docs.meetjamie.ai/developers/api/api",
  },
  {
    id: "otter",
    name: "Otter.ai",
    vendor: "Otter.ai",
    category: "meetings",
    featured: false,
    logo: "otter",
    tagline: "Conversations, summaries and action items from Otter.",
    auth: ["token", "mcp"],
    provider: "otter",
    reads: ["Conversations, transcripts, summaries and action items"],
    writes: [],
    mcp: MCP("https://mcp.otter.ai/mcp"),
    status: "ready",
    notes: [
      "Syncing needs an API key from Otter → Integrations → Developer, which only Enterprise workspaces have.",
      "The MCP connection works on other plans and lets the assistant search your Otter meetings live.",
    ],
    docsUrl: "https://help.otter.ai/hc/en-us/articles/36130822688279-Otter-ai-Public-API",
  },
  {
    id: "read_ai",
    name: "Read AI",
    vendor: "Read AI",
    category: "meetings",
    featured: false,
    logo: "readai",
    tagline: "Ask about your Read AI meeting reports, transcripts and action items.",
    auth: ["mcp"],
    reads: ["Meeting reports, transcripts, summaries and action items"],
    writes: [],
    mcp: MCP("https://api.read.ai/mcp"),
    status: "ready",
    notes: ["Read AI's API only signs in through the browser and has no personal keys yet, so Ensemble reaches it through its MCP server (open beta)."],
    docsUrl: "https://support.read.ai/hc/en-us/articles/49379985941523-Read-AI-API-and-MCP-Overview",
  },
  {
    id: "avoma",
    name: "Avoma",
    vendor: "Avoma",
    category: "meetings",
    featured: false,
    logo: "avoma",
    tagline: "Ask about recorded calls, notes and action items.",
    auth: ["mcp"],
    reads: ["Meetings, transcripts and notes"],
    writes: [],
    mcp: MCP("https://mcp.avoma.com/mcp"),
    status: "ready",
    notes: ["Avoma's API needs a paid plan."],
  },
  {
    id: "gong",
    name: "Gong",
    vendor: "Gong",
    category: "meetings",
    featured: false,
    logo: "gong",
    tagline: "Ask about recorded customer calls and deals.",
    auth: ["mcp"],
    reads: ["Calls, transcripts and deal context"],
    writes: [],
    mcp: MCP("https://mcp.gong.io/mcp"),
    status: "ready",
    notes: ["Your Gong admin may need to allow MCP access."],
  },
  {
    id: "grain",
    name: "Grain",
    vendor: "Grain",
    category: "meetings",
    featured: false,
    logo: "grain",
    tagline: "Ask about recorded meetings, notes and highlights.",
    auth: ["mcp"],
    reads: ["Recordings, transcripts and notes"],
    writes: [],
    mcp: MCP("https://api.grain.com/_/mcp"),
    status: "ready",
  },
  {
    id: "fellow",
    name: "Fellow",
    vendor: "Fellow",
    category: "meetings",
    featured: false,
    logo: "fellow",
    tagline: "Ask about meeting notes, agendas and action items.",
    auth: ["mcp"],
    reads: ["Meeting notes, recordings and action items"],
    writes: [],
    mcp: MCP("https://fellow.app/mcp"),
    status: "ready",
  },
  {
    id: "supernormal",
    name: "Supernormal",
    vendor: "Supernormal",
    category: "meetings",
    featured: false,
    logo: "supernormal",
    tagline: "Ask about meeting notes and transcripts.",
    auth: ["mcp"],
    reads: ["Meeting notes and transcripts"],
    writes: [],
    mcp: MCP("https://api.supernormal.com/mcp"),
    status: "ready",
  },
  {
    id: "meetgeek",
    name: "MeetGeek",
    vendor: "MeetGeek",
    category: "meetings",
    featured: false,
    logo: "meetgeek",
    tagline: "Ask about meeting recordings, summaries and highlights.",
    auth: ["mcp"],
    reads: ["Meetings, transcripts and summaries"],
    writes: [],
    mcp: MCP("https://mcp.meetgeek.ai/mcp"),
    status: "ready",
  },
  {
    id: "bluedot",
    name: "Bluedot",
    vendor: "Bluedot",
    category: "meetings",
    featured: false,
    logo: "bluedot",
    tagline: "Ask about recorded meetings and their notes.",
    auth: ["mcp"],
    reads: ["Meeting notes and transcripts"],
    writes: [],
    mcp: MCP("https://app.bluedothq.com/api/v1/mcp"),
    status: "ready",
    notes: ["Bluedot has no REST API; the MCP server is the only way in."],
  },
  {
    id: "tactiq",
    name: "Tactiq",
    vendor: "Tactiq",
    category: "meetings",
    featured: false,
    logo: "tactiq",
    tagline: "Ask about live-captioned meeting transcripts.",
    auth: ["mcp"],
    reads: ["Meeting transcripts and summaries"],
    writes: [],
    mcp: MCP("https://mcp.tactiq.io"),
    status: "ready",
    notes: ["Tactiq has no REST API; the MCP server is the only way in."],
  },
  {
    id: "loom",
    name: "Loom",
    vendor: "Atlassian",
    category: "meetings",
    featured: false,
    logo: "loom",
    tagline: "Video messages and their transcripts.",
    auth: ["mcp"],
    reads: ["Videos and transcripts"],
    writes: [],
    status: "soon",
    notes: ["Loom has no public API for transcripts. A Loom workspace linked to an Atlassian site can be reached through the Atlassian Rovo MCP server (the Jira entry)."],
  },
  {
    id: "docusign",
    name: "Docusign",
    vendor: "Docusign",
    category: "sign",
    featured: false,
    logo: "docusign",
    tagline: "Envelope status: what is waiting for whom, and what was completed.",
    auth: ["oauth"],
    provider: "docusign",
    reads: ["Envelopes and their status"],
    writes: [],
    status: "ready",
  },
  {
    id: "canva",
    name: "Canva",
    vendor: "Canva",
    category: "design",
    featured: false,
    logo: "canva",
    tagline: "Find, create and export designs from the assistant.",
    auth: ["mcp"],
    reads: ["Designs and brand assets"],
    writes: ["New and edited designs"],
    mcp: MCP("https://mcp.canva.com/mcp"),
    status: "ready",
  },
  {
    id: "miro",
    name: "Miro",
    vendor: "Miro",
    category: "design",
    featured: false,
    logo: "miro",
    tagline: "Read boards and add stickies, frames and diagrams.",
    auth: ["mcp"],
    reads: ["Boards"],
    writes: ["Stickies, frames and diagrams"],
    mcp: MCP("https://mcp.miro.com"),
    status: "ready",
  },
  {
    id: "webflow",
    name: "Webflow",
    vendor: "Webflow",
    category: "design",
    featured: false,
    logo: "webflow",
    tagline: "Sites, pages and CMS items.",
    auth: ["mcp"],
    reads: ["Sites, pages and CMS"],
    writes: ["Pages and CMS items"],
    mcp: MCP("https://mcp.webflow.com/mcp"),
    status: "ready",
  },
  {
    id: "sentry",
    name: "Sentry",
    vendor: "Sentry",
    category: "developer",
    featured: false,
    logo: "sentry",
    tagline: "Triage issues, read stack traces and releases.",
    auth: ["mcp"],
    reads: ["Issues, events and releases"],
    writes: ["Issue status and assignment"],
    mcp: MCP("https://mcp.sentry.dev/mcp"),
    status: "ready",
  },
  {
    id: "stripe",
    name: "Stripe",
    vendor: "Stripe",
    category: "sales_support",
    featured: false,
    logo: "stripe",
    tagline: "Customers, payments and subscriptions.",
    auth: ["mcp"],
    reads: ["Customers, payments, invoices and subscriptions"],
    writes: ["Stripe objects through its API"],
    mcp: MCP("https://mcp.stripe.com"),
    status: "ready",
  },
  {
    id: "supabase",
    name: "Supabase",
    vendor: "Supabase",
    category: "developer",
    featured: false,
    logo: "supabase",
    tagline: "Projects, tables and SQL.",
    auth: ["mcp"],
    reads: ["Projects and databases"],
    writes: ["Database changes"],
    mcp: MCP("https://mcp.supabase.com/mcp"),
    status: "ready",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    vendor: "Hugging Face",
    category: "developer",
    featured: false,
    logo: "huggingface",
    tagline: "Search models, datasets and Spaces.",
    auth: ["mcp"],
    reads: ["Models, datasets, Spaces and papers"],
    writes: [],
    mcp: MCP("https://huggingface.co/mcp"),
    status: "ready",
  },
  {
    id: "zapier",
    name: "Zapier",
    vendor: "Zapier",
    category: "developer",
    featured: false,
    logo: "zapier",
    tagline: "Reach thousands of other apps through your Zapier actions.",
    auth: ["mcp"],
    reads: ["Whatever your Zapier actions read"],
    writes: ["Whatever your Zapier actions do"],
    mcp: MCP("https://mcp.zapier.com/api/v1/connect"),
    status: "ready",
  },
  { id: "figma", name: "Figma", vendor: "Figma", category: "design", featured: false, logo: "figma", tagline: "Design context and screenshots.", auth: ["mcp"], reads: ["Files and frames"], writes: [], status: "soon", notes: ["Figma only allows approved clients on its remote MCP server."] },
  { id: "dropbox", name: "Dropbox", vendor: "Dropbox", category: "files_docs", featured: false, logo: "dropbox", tagline: "Files and Paper docs.", auth: ["mcp"], reads: ["Files"], writes: [], status: "soon", notes: ["Dropbox's MCP server only accepts a trusted set of clients for now."] },
  { id: "box", name: "Box", vendor: "Box", category: "files_docs", featured: false, logo: "box", tagline: "Files and folders.", auth: ["oauth"], reads: ["Files"], writes: [], status: "soon" },
  { id: "hubspot", name: "HubSpot", vendor: "HubSpot", category: "sales_support", featured: false, logo: "hubspot", tagline: "Contacts, companies and deals.", auth: ["oauth"], reads: ["CRM records"], writes: [], status: "soon" },
  { id: "intercom", name: "Intercom", vendor: "Intercom", category: "sales_support", featured: false, logo: "intercom", tagline: "Conversations and help articles.", auth: ["mcp"], reads: ["Conversations and contacts"], writes: [], status: "soon" },
  { id: "vercel", name: "Vercel", vendor: "Vercel", category: "developer", featured: false, logo: "vercel", tagline: "Deployments and logs.", auth: ["mcp"], reads: ["Projects, deployments and logs"], writes: [], status: "soon", notes: ["Vercel reviews each MCP client before it can connect."] },
  { id: "cloudflare", name: "Cloudflare", vendor: "Cloudflare", category: "cloud", featured: false, logo: "cloudflare", tagline: "Workers, DNS, analytics and docs.", auth: ["mcp"], reads: ["Account resources"], writes: [], status: "soon" },
  { id: "grafana", name: "Grafana Cloud", vendor: "Grafana Labs", category: "cloud", featured: false, logo: "grafana", tagline: "Metrics, logs, traces and alerts.", auth: ["mcp"], reads: ["Dashboards, metrics, logs and alerts"], writes: [], status: "soon" },
  { id: "aws", name: "AWS", vendor: "Amazon Web Services", category: "cloud", featured: false, logo: "aws", tagline: "Resources and documentation.", auth: ["mcp"], reads: ["Account resources"], writes: [], status: "soon" },
  { id: "azure", name: "Azure", vendor: "Microsoft", category: "cloud", featured: false, logo: "azure", tagline: "Azure DevOps work items, repos and pipelines.", auth: ["oauth"], reads: ["Work items, repos and pipelines"], writes: [], status: "soon" },
  {
    id: "csv",
    name: "CSV or spreadsheet",
    vendor: "Any app",
    category: "work_tracking",
    featured: false,
    logo: "csv",
    tagline: "Import tasks from any CSV export, mapping your own columns.",
    auth: ["file"],
    reads: [],
    writes: [],
    import: { source: "csv", files: ["csv", "tsv"], api: false, brings: ["Rows as tasks with due dates, tags, status and projects"] },
    status: "ready",
  },
  ...MORE_MCP_APPS,
  ...MORE_SOON,
];

export function catalogEntry(id: string): ConnectorCatalogEntry | undefined {
  return CONNECTOR_CATALOG.find((entry) => entry.id === id);
}

/** The five shown in Settings → Connections; everything else is in Browse connectors. */
export const FEATURED_CONNECTORS: readonly string[] = CONNECTOR_CATALOG.filter((entry) => entry.featured).map((entry) => entry.id);
