# Round 3 gallery content. One card per SLOT; every card shows both Minimal flavours side by side.
# cmp = where the Expressive version of the same slot lives (for the suite switcher).
SECTIONS = [
  ("work", "Agent at work", "Thinking, streaming, tools and runs: the moments people see most, so they get the least motion."),
  ("load", "Loading & sync", "Getting content onto the screen without a show."),
  ("turn", "Your turn", "When the agent waits for you, and the small closure after you act."),
  ("trouble", "Trouble", "Errors and lost connections: calm, clear, and quick to recover."),
  ("brand", "Brand, touch & native", "The splash, everyday controls, and the menu-bar icon."),
]
C = lambda **k: k
CARDS = [
  C(sec="work", id="thinking", no="01", slot="agent.thinking", name="Thinking + status", span=3, h=270, cmp=("r1", "s-glyph"),
    where="Assistant dock header, <code>@ensemble</code> inline in docs, job rows (14 px).",
    quiet="A short violet segment glides along the hairline mark and back, with the inner strand following in step. Status text crossfades (no letter drops) and the elapsed time counts up in mono.",
    dot="The agent dot breathes next to your dot. That is the whole animation. Status text crossfades.",
    reduced="Static U or dots; the real status text swaps.", tokens="--m-dur-loop 3.2 s · --m-ease-loop"),
  C(sec="work", id="stream", no="02", slot="reply.stream", name="Streaming reply", span=3, h=270, cmp=("r1", "s-agent"),
    where="Assistant replies, <code>.ensemble-reply</code> in docs and threads.",
    quiet="Words fade in with no colour shift behind a 1 px violet caret. When the reply finishes, a hairline rule draws under it and the sources line fades in.",
    dot="The caret is a single agent dot that rides the end of the text, then fades out when the reply is done.",
    reduced="Text appears in chunks, with no caret.", tokens="--m-dur-ui 420 ms · --m-ease-enter"),
  C(sec="work", id="tool", no="03", slot="tool.call", name="Tool calls", span=3, h=280, cmp=("r1", "s-agent"),
    where="ToolCall rows in the dock and in run details.",
    quiet="16 px line icons: running is a hairline ring with a slow arc, done draws a muted check, pending is an open violet ring, failed is a red dash.",
    dot="Every state is one dot: a breathing agent dot while running, a filled dot when done, an open ring when pending, a red dot when failed.",
    reduced="Static icon per state.", tokens="--m-dur-ui · --m-ease-move"),
  C(sec="work", id="run", no="04", slot="run.progress", name="Run progress", span=3, h=280, cmp=("r1", "s-run"),
    where="Job cards (replaces the spinner), TaskAgentPanel, Runs timeline.",
    quiet="A 1 px track with five ticks. The violet fill eases to each step, a small head dot breathes at the front, and the step label crossfades.",
    dot="Five dots: filled when done, the agent dot breathing on the current step, open rings for the steps still to come.",
    reduced="Static fill and label.", tokens="--m-dur-move 640 ms · --m-ease-move"),
  C(sec="load", id="progress", no="05", slot="page.progress", name="Page progress", span=3, h=270, cmp=("r1", "s-route"),
    where="Route changes (Today, Board, Context, Runs, Needs me).",
    quiet="A 1.5 px top line that trickles in three calm steps and fades as the page content rises 4 px in a short stagger.",
    dot="A single agent dot travels along the top edge, the same way the line would fill.",
    reduced="Content appears; no bar.", tokens="--m-ease-move · stagger 70 ms"),
  C(sec="load", id="skeleton", no="06", slot="content.skeleton", name="Skeleton", span=3, h=270, cmp=("r1", "s-skel"),
    where="Today list, Board columns, Runs, peek panel.",
    quiet="Low-contrast blocks that breathe together very slowly. No shimmer and no sweep. The content crossfades in when it arrives.",
    dot="The text lines become hairlines, and one agent dot moves down the margin row by row, as if it were reading.",
    reduced="Static tinted blocks.", tokens="--m-dur-loop · opacity only"),
  C(sec="load", id="fetch", no="07", slot="fetch.refresh", name="Fetch now", span=3, h=280, cmp=("r1", "s-sync"),
    where="Topbar Fetch now button, 09:00/16:00 scheduled fetch.",
    quiet="Two concentric hairline arcs (the two strands) turn together with an eased start and stop, then the new rows slide down 4 px.",
    dot="The two dots swap places in slow half turns, like a quiet refresh.",
    reduced="The count updates; the icon stays still.", tokens="--m-ease-loop 1.5 s/turn"),
  C(sec="load", id="sync", no="08", slot="connector.sync", name="Connector sync", span=3, h=280, cmp=("r1", "s-sync"),
    where="Onboarding, Settings → Connections, the sidebar sync status.",
    quiet="Hairlines run from each source into a small U. One violet bead drifts along each line while the counts ease up, and the lines dim when the sync is done.",
    dot="Each source has one status dot: breathing while it syncs, filled when it is done.",
    reduced="Final counts, with a “Synced” label.", tokens="--m-ease-loop · --m-ease-move"),
  C(sec="turn", id="needs", no="09", slot="needs.waiting", name="Needs you", span=3, h=270, cmp=("r1", "s-needs"),
    where="<code>waiting_approval</code>, the Needs me page, editor-hook decisions.",
    quiet="The agent strand holds still while your strand breathes in violet, which says it is your turn. A 1 px timeout line drains along the bottom of the card.",
    dot="The agent dot stays solid and your dot breathes. The timeout is the only line.",
    reduced="Static strands with a countdown in text.", tokens="--m-dur-loop · linear drain"),
  C(sec="turn", id="approve", no="10", slot="action.approve", name="Approve", span=3, h=270, cmp=("r2", "p-confetti"),
    where="Approve / Allow once / Apply / Mark done.",
    quiet="The press scales the button by only 1.5%. A thin violet check draws in and the label crossfades to Approved. The card then folds away, leaving an Undo line.",
    dot="Your dot slides into the agent dot, so the two become one (the handoff), then the card folds away.",
    reduced="Instant approved state.", tokens="--m-scale-press .985 · --m-dur-move"),
  C(sec="turn", id="celebrate", no="11", slot="moment.celebrate", name="All clear (subtle celebration)", span=6, h=270, cmp=("r2", "p-tapestry"),
    where="Needs me reaching zero, and the daily streak.",
    quiet="The last row lifts away and the hairline mark draws once. A single faint ring opens and fades, the italic line appears, and the streak digit crossfades. No confetti.",
    dot="The two dots merge into one and a single faint ring opens once.",
    reduced="The final line and streak, shown still.", tokens="one ring · opacity ≤ .35"),
  C(sec="trouble", id="error", no="12", slot="state.error", name="Error + retry", span=3, h=250, cmp=("r1", "s-kill"),
    where="Failed connector fetches, job errors, expired tokens.",
    quiet="The two halves of the mark part by a few pixels and turn a muted red. On Retry they ease back together and the text crossfades to recovered.",
    dot="The dots drift apart and the agent dot goes hollow. While retrying it breathes, then the dots rejoin.",
    reduced="Static error, then an instant recovered state.", tokens="--m-dur-move · amp 3 px"),
  C(sec="trouble", id="connection", no="13", slot="net.connection", name="Offline → online", span=3, h=250, cmp=("r2", "p-retie"),
    where="Sidebar status, SSE drop (live.tsx), AuthGate reconnecting.",
    quiet="A dashed hairline links you and Ensemble. The dashes drift while it reconnects, then a solid violet line draws over them, and the pill fades once you are back online.",
    dot="One status dot: an open ring when offline, a small breathing core while it reconnects, filled once it is back.",
    reduced="Text states only.", tokens="--m-dur-move · --m-ease-exit"),
  C(sec="brand", id="splash", no="14", slot="brand.splash", name="Splash", span=6, h=300, cmp=("r2", "p-reveals"),
    where="App launch, AuthGate first paint, About.",
    quiet="The logo itself, the Two-voices mark at full weight: the violet agent strand draws, then the you strand, then the wordmark fades up 4 px.",
    dot="Two dots, the agent and you, arrive at the tops of the mark and each draws its own strand; the dots hand over to the round caps and the wordmark fades in. It always lands on the mark.",
    reduced="The final lockup (the mark and wordmark), with a fade.", tokens="draw 1.4 s · --m-ease-move"),
  C(sec="brand", id="controls", no="15", slot="control.*", name="Button · Toggle · Checkbox · Tabs · Focus", span=6, h=300, cmp=("r2", "p-microa"),
    where="Every control in the app. Try them: they are live.",
    quiet="1 px borders and a 1.5% press. The toggle knob fills violet. The check draws in. The tab underline is 1.5 px and slides without stretching. On focus, the border turns violet with no glow.",
    dot="The button gets a dot on hover. The toggle knob is your dot, and it becomes the agent dot when on. The checkbox fills with a dot. A dot marks the active tab. Focus lights a dot inside the field.",
    reduced="State changes with no travel.", tokens="--m-dur-micro 200 ms · --m-dur-ui"),
  C(sec="brand", id="tray", no="16", slot="native.tray", name="Menu-bar / tray states", span=6, h=330, cmp=("r2", "p-tray"),
    where="macOS menu-bar extra, Windows/Linux tray (16 and 22 px). Standalone SVGs are in <code>components/tray/svg/</code>.",
    quiet="The same hinted Two-voices mark as every other style, with hairline cues. Working runs a segment along the you strand, syncing runs dashes along the agent strand, needs adds a corner dot, paused parts the mark at the bottom, done adds a corner tick, error parts the agent strand in red, and offline dots the whole mark.",
    dot="The same hinted mark, with dot cues. Working dots the you strand, syncing dots the agent strand, needs adds a violet corner dot, paused parts the mark with a dot in the gap, done adds a ringed dot, error adds a red dot, and offline shows the mark in faint dots.",
    reduced="Static pose per state.", tokens="template-safe · hinted 22 px U (3 / 1 / 2 px)"),
]
TOUR = ""
HIGHLIGHTS = "cmp:thinking@3200;p-thinking,p-stream@2800;p-tool,p-run@3400;p-needs,p-approve@3200;p-celebrate@3200;p-error,p-connection@4600;p-splash@2800;p-controls@4400;p-tray@2200"
