#!/usr/bin/env python3
"""One source of truth for the motion suite -> components/core/suite.css + motion-themes.json.
Each theme fills the same token contract; components only ever read tokens, never theme names."""
import json, pathlib
R = pathlib.Path(__file__).resolve().parent.parent
# Contract: every theme must define every key.
THEMES = {
  "expressive": {
    "label": "Expressive", "source": "rounds 1-2",
    "ease-enter": "cubic-bezier(.22,1,.36,1)", "ease-move": "cubic-bezier(.34,1.3,.64,1)", "ease-exit": "cubic-bezier(.4,0,1,1)", "ease-loop": "cubic-bezier(.65,0,.35,1)",
    "spring": "soft", "dur-micro": 160, "dur-ui": 320, "dur-move": 870, "dur-loop": 4800,
    "amp": 12, "scale-press": .96, "overshoot": 1, "stroke": 2.5, "ornament": 1, "particles": 1, "color-mode": "duo",
    "note": "Springs with overshoot, braids, sparks, confetti. The default."},
  "minimal-quiet": {
    "label": "Minimal · Quiet", "source": "round 3",
    "ease-enter": "cubic-bezier(.25,.1,.25,1)", "ease-move": "cubic-bezier(.33,0,.2,1)", "ease-exit": "cubic-bezier(.4,0,.6,1)", "ease-loop": "cubic-bezier(.45,0,.55,1)",
    "spring": "none", "dur-micro": 200, "dur-ui": 420, "dur-move": 640, "dur-loop": 3200,
    "amp": 4, "scale-press": .985, "overshoot": 0, "stroke": 1.5, "ornament": 0, "particles": 0, "color-mode": "mono+accent",
    "note": "Hairline strokes, one violet accent, slow sine drift. Nothing overshoots."},
  "minimal-dot": {
    "label": "Minimal · Dot", "source": "round 3",
    "ease-enter": "cubic-bezier(.25,.1,.25,1)", "ease-move": "cubic-bezier(.33,0,.2,1)", "ease-exit": "cubic-bezier(.4,0,.6,1)", "ease-loop": "cubic-bezier(.45,0,.55,1)",
    "spring": "none", "dur-micro": 200, "dur-ui": 480, "dur-move": 720, "dur-loop": 2800,
    "amp": 3, "scale-press": .99, "overshoot": 0, "stroke": 1, "ornament": 0, "particles": 0, "color-mode": "mono+accent",
    "note": "Only two dots (you + agent) and at most one line. States are told by fill, ring and position."},
  "reduced": {
    "label": "Reduced (overlay)", "source": "OS / app setting",
    "ease-enter": "linear", "ease-move": "linear", "ease-exit": "linear", "ease-loop": "linear",
    "spring": "none", "dur-micro": 0, "dur-ui": 150, "dur-move": 0, "dur-loop": 0,
    "amp": 0, "scale-press": 1, "overshoot": 0, "stroke": 1.5, "ornament": 0, "particles": 0, "color-mode": "inherit",
    "note": "Not a style: an overlay on any style. Crossfades of 150 ms or less, loops become still poses."},
}
MS = {"dur-micro", "dur-ui", "dur-move", "dur-loop"}
def val(k, v):
    if k in MS: return f"{v}ms"
    if k == "amp": return f"{v}px"
    if k == "stroke": return f"{v}px"
    return str(v)
SKIP = {"label", "source", "note", "spring", "color-mode"}
css = ["/* GENERATED by tools/gen_tokens.py: the motion-suite token contract. Do not edit by hand. */",
       "/* Every theme defines the same --m-* tokens. Components read tokens only; switching a theme is one attribute: */",
       "/*   <html data-motion-theme=\"minimal-quiet\">   (expressive | minimal-quiet | minimal-dot)                  */"]
for name, t in THEMES.items():
    if name == "reduced": continue
    sel = ':root, [data-motion-theme="expressive"]' if name == "expressive" else f'[data-motion-theme="{name}"]'
    body = " ".join(f"--m-{k}: {val(k, v)};" for k, v in t.items() if k not in SKIP)
    css.append(f"{sel} {{ {body} }}")
red = " ".join(f"--m-{k}: {val(k, v)};" for k, v in THEMES["reduced"].items() if k not in SKIP | {"stroke"})
css.append(f"@media (prefers-reduced-motion: reduce) {{ :root, [data-motion-theme] {{ {red} }} }}")
css.append(f'[data-reduce-motion="true"], [data-reduce-motion="true"] [data-motion-theme] {{ {red} }}')
(R / "components/core/suite.css").write_text("\n".join(css) + "\n")
SLOTS = json.loads((R / "tools/slots.json").read_text())
(R / "components/core/motion-themes.json").write_text(json.dumps({"version": 1, "fallback": {"minimal-dot": "minimal-quiet", "minimal-quiet": "expressive"},
    "themes": THEMES, "slots": SLOTS}, indent=2, ensure_ascii=False) + "\n")
print("suite.css + motion-themes.json", len(SLOTS), "slots")
