# Gallery content: one entry per piece. span is out of 6 columns; h = stage height.
SECTIONS = [
  ("celebrate", "Celebrate", "Small, earned moments of joy. Short, never blocking."),
  ("arrive", "Arrive", "First run, connecting sources, and the morning briefing."),
  ("together", "Together", "You and the agent working on the same things at the same time."),
  ("touch", "Touch", "Micro-interactions: every control has a bit of thread tension."),
  ("rest", "Listen & rest", "Voice mode, ambient idle, and the theme switch."),
  ("recover", "Recover & native", "Getting back on track, and the menu-bar icon for the desktop apps."),
  ("brand", "Brand", "Logo reveals for the launch screen and landing page."),
]
HERO = dict(id="brandloop", no="00", name="Brand loop: two ribbons", span=6, h=420,
  where="Landing page hero, app launch, About screen, marketing video bumper.",
  idea="Two twisting ribbons (violet agent, paper you) trace the mark, a figure-eight and a pair of linked rings, then fold back into the mark. The ribbons turn in 3D, so you see the lighter back when they twist. It is a seamless 12 s loop.",
  reduced="The static icon ribbons with no twisting.", ease="custom sine timeline with a spring-gentle settle")
CARDS = [
  dict(sec="celebrate", id="confetti", no="01", name="Strand confetti", span=2, h=330,
    where="Checking off a task on Today, the Board, or Mark done (triage <code>d</code>).",
    idea="The checkbox <b>ties</b>, a thread strikes through the title, and a burst of tiny <b>curled strands</b> tumbles out under real physics (gravity, drag, flutter). The day's bead thread then gains a bead.",
    reduced="Instant check and strike-through; the bead fills without the burst.", ease="spring-bouncy · physics"),
  dict(sec="celebrate", id="tapestry", no="02", name="Inbox zero tapestry", span=2, h=330, dwell=6200,
    where="Needs me when the last item is cleared, and the sidebar Needs me badge reaching 0.",
    idea="Each cleared card folds into a thread. The threads <b>weave</b> row by row, following a shuttle, into a small tapestry with the mark woven in. It hangs from a rod and its fringe sways.",
    reduced="The finished tapestry appears fully woven and doesn't sway.", ease="spring-soft per cell · boustrophedon stagger"),
  dict(sec="celebrate", id="streak", no="03", name="Streak knot", span=2, h=330,
    where="Today header and the weekly recap: days in a row that Needs me was cleared.",
    idea="The week is a thread of beads. Today's bead <b>drops onto the thread</b>, which dips under the weight and springs back. A knot ties around the bead and the counter rolls to the next number.",
    reduced="The bead appears in place and the number updates.", ease="gravity + spring-pluck thread + spring-bouncy digits"),
  dict(sec="arrive", id="meet", no="04", name="First meeting", span=4, h=400, dwell=7200,
    where="Onboarding step 1 and the very first launch, after sign-in.",
    idea="<b>You</b> (paper) and <b>your agent</b> (violet) arrive from opposite sides. They spiral around each other, meet at the bottom, and <b>grow up the arms into the mark</b>. The tile settles in and the wordmark follows.",
    reduced="The final icon and wordmark, with a fade.", ease="spiral r(t)=(1−t)^2.2 · spring-gentle tile"),
  dict(sec="arrive", id="connect", no="05", name="Connect a source", span=2, h=400, dwell=6400,
    where="Onboarding and Settings → Connections, when a Gmail, GitHub, Slack or Calendar OAuth finishes.",
    idea="A thread shoots from the source to Ensemble, gets <b>plucked taut</b> and wobbles, and a knot ties in the middle. Items then flow across as beads while the count climbs.",
    reduced="The line is drawn solid, the count jumps to its final value, and the check appears.", ease="spring-pluck"),
  dict(sec="arrive", id="sunrise", no="06", name="Morning briefing", span=6, h=420, dwell=7000,
    where="The first Today visit of the day (before about 11:00), and the 09:00 scheduled fetch.",
    idea="A sun <b>rises out of the mark</b> with strand rays and the sky warms. A thread then drops from the mark and the briefing cards <b>unfold like paper</b> along it, each pinned by a bead.",
    reduced="The cards fade in and the sun is shown static above the mark.", ease="spring-gentle rise · rotateX unfold"),
  dict(sec="together", id="coedit", no="07", name="Co-editing threads", span=3, h=360, dwell=8200,
    where="Documents and comment threads when the agent edits alongside you (the <code>@ensemble</code> inline).",
    idea="Presence <b>cursors leave threads</b>: short trails that fade when a cursor rests. The agent's typing inks in violet. When your cursors meet, a thread briefly <b>links the two flags</b>, and an accepted suggestion knits into the text.",
    reduced="The cursors jump to position with no trails, and text appears without the ink-in.", ease="spring-soft cursors"),
  dict(sec="together", id="graph", no="08", name="Graph bloom & focus ripple", span=3, h=360, dwell=7600,
    where="Context graph: first load, filters, and selecting a node (click any node to try it).",
    idea="Nodes <b>bloom</b> outward in BFS order. Each edge is <b>knitted</b> by a needle as a dashed stitch that pulls tight into a line. Selecting a node sends a ripple and beads to its neighbours, and the rest of the graph dims.",
    reduced="The graph appears at once; selecting a node just highlights it and its neighbours.", ease="spring-bouncy nodes · stitch tighten"),
  dict(sec="together", id="board", no="09", name="Board handoff", span=6, h=300, dwell=9400,
    where="Board: Assign to agent (triage <code>a</code>), the agent finishing a card, and you dragging a card.",
    idea="A violet <b>thread lowers</b>, hooks your card, and <b>carries it</b> to the Ensemble column, tilting with its speed. The owner dot morphs. When the work is done the card hops to Done. Your own drags leave a <b>tethered ghost</b> tied to a stitched slot.",
    reduced="Cards swap columns instantly, with the owner shown by a colour change.", ease="spring-soft x/y · tilt ∝ velocity"),
  dict(sec="touch", id="microa", no="10", name="Button · Toggle · Checkbox", span=3, h=300, dwell=7000,
    where="The primary buttons (Approve, Allow once), the Settings toggles, and the checklists everywhere.",
    idea="Buttons carry a <b>thread</b>: it sags at rest, goes taut on hover and is pressed down on click, then plucks back. The toggle's knob is <b>the Mark's two dots</b> and they swap sides as it slides. The checkbox <b>ties a little knot</b> that pulls tight into a check.",
    reduced="Instant state changes.", ease="spring-pluck · spring-soft · point-morph"),
  dict(sec="touch", id="microb", no="11", name="Tabs · Bell · Focus rim", span=3, h=300, dwell=6400,
    where="The view tabs (Today/Board/Context/Runs), the notification bell, and the ask bar and inputs.",
    idea="The tab underline is a <b>stretchy thread</b>: its leading end runs ahead and it sags mid-flight. A <b>strand wraps around the bell</b> as it swings. On focus, <b>two strands race around the input</b> from the left and meet on the right.",
    reduced="The underline jumps, the bell doesn't swing, and the rim appears.", ease="spring-snappy lead · spring-soft trail"),
  dict(sec="rest", id="voice", no="12", name="Voice: in sync", span=4, h=380, dwell=11000,
    where="Voice / listening mode (push-to-talk in the dock and on mobile).",
    idea="Your voice and the agent's are <b>two waves</b>. As it understands you, the agent's wave matches your frequency and phase until the two <b>lock into one</b> (literally <i>in sync</i>). Then the agent leads while it speaks.",
    reduced="Static waves; the states are shown as text only.", ease="phase-lock lerp · harmonic sum"),
  dict(sec="rest", id="ambient", no="13", name="Ambient + theme morph", span=2, h=380, dwell=6800,
    where="The sidebar logo when idle, and the theme toggle (Settings, ⌘⇧L).",
    idea="The sidebar U <b>breathes</b> (the strands inhale out of phase) and a bead drifts along it now and then. The theme toggle morphs a strand <b>sun into a moon</b> and the theme <b>washes in</b> from the button.",
    reduced="A static logo; the theme switches instantly.", ease="inOutSine 6 s breath · spring-soft morph"),
  dict(sec="recover", id="retie", no="14", name="Re-tie & reconnect", span=3, h=340, dwell=7600,
    where="Failed connector fetches and job errors (Retry), and the sidebar Offline → Online status.",
    idea="The snapped thread's frayed ends <b>reach for each other</b>, tie a knot and pull taut. Red turns violet, then green. When you're back online, the Mark's middle dot pops back in and the dashes close into a line.",
    reduced="A crossfade from the error state to the fixed state.", ease="spring-soft ends · spring-pluck taut"),
  dict(sec="recover", id="tray", no="15", name="Menu-bar / tray states", span=3, h=340, dwell=6000,
    where="The macOS menu-bar extra and the Windows/Linux tray icon for the native app (16 and 22 px).",
    idea="Nine tiny states, each <b>readable from motion alone</b> at 16 px: dashes chase in opposite directions for working, a bead runs the mark when syncing, and there's a ping for needs you. Shown both as template (mono) and in colour.",
    reduced="Static icon per state.", ease="linear loops (tiny sizes need constant speed)"),
  dict(sec="brand", id="reveals", no="16", name="Logo reveals", span=6, h=440, dwell=10400,
    where="App launch, the landing page intro, and video bumpers. Three variants to choose from.",
    idea="<b>A · Pull:</b> one taut thread is plucked, pulled down into a U, and splits into two voices. <b>B · Woven:</b> warp and weft strips weave the tile, then the mark is stitched on. <b>C · Needle:</b> a needle threads the letters of the wordmark and ties the dot on the i.",
    reduced="The final lockup with a fade.", ease="spring-pluck · spring-gentle"),
]
TOUR = "p-brandloop@4200;p-confetti,p-tapestry,p-streak;p-meet,p-connect;p-sunrise;p-coedit,p-graph;p-board;p-microa,p-microb;p-voice,p-ambient;p-retie,p-tray;p-reveals"
HIGHLIGHTS = "p-brandloop@4200;p-confetti,p-tapestry,p-streak@5600;p-meet,p-connect@6100;p-board@8300;p-voice,p-ambient@7600;p-reveals@7000"
