export type RouteCheck = "happy-path" | "isolation" | "unknown-id" | "invalid-input" | "relation-isolation" | "hosted-verification";

// Explicit request contracts, not a guess from route/test file names.
export const authRouteCoverage: Readonly<Record<string, readonly RouteCheck[]>> = {
  "GET /api/auth/status": ["happy-path"],
  "POST /api/auth/signup": ["happy-path", "invalid-input"],
  "POST /api/auth/login": ["happy-path", "invalid-input"],
  "POST /api/auth/logout": ["happy-path"],
  "GET /api/auth/me": ["happy-path"],
  "PATCH /api/auth/me": ["happy-path", "invalid-input"],
  "PUT /api/auth/profile": ["happy-path", "invalid-input"],
  "POST /api/auth/verify-email": ["happy-path", "isolation", "invalid-input"],
  "POST /api/auth/resend-verification": ["happy-path"],
  "POST /api/auth/forgot": ["happy-path", "invalid-input"],
  "POST /api/auth/reset": ["happy-path", "invalid-input"],
  "GET /api/auth/identities": ["happy-path"],
  "DELETE /api/auth/identities/:provider": ["happy-path", "invalid-input"],
  "GET /api/auth/export": ["happy-path", "isolation"],
  "DELETE /api/auth/account": ["happy-path", "invalid-input"],
  "GET /api/auth/oauth/:provider/start": ["happy-path"],
  "GET /api/auth/oauth/:provider/callback": ["happy-path", "invalid-input"],
};

export const cliAuthRouteCoverage: Readonly<Record<string, readonly RouteCheck[]>> = {
  "POST /api/cli/auth/start": ["happy-path", "invalid-input"],
  "GET /api/cli/auth/request": ["happy-path", "unknown-id"],
  "POST /api/cli/auth/approve": ["happy-path", "invalid-input"],
  "POST /api/cli/auth/token": ["happy-path", "invalid-input"],
  "POST /api/cli/logout": ["happy-path"],
};

export const mcpRouteCoverage: Readonly<Record<string, readonly RouteCheck[]>> = {
  "POST /mcp": ["happy-path", "isolation"],
  "GET /mcp": ["invalid-input"],
  "DELETE /mcp": ["invalid-input"],
};

export const resourceRouteCoverage: Readonly<Record<string, readonly RouteCheck[]>> = {
  "GET /api/tasks": ["happy-path", "isolation"],
  "POST /api/tasks": ["happy-path", "invalid-input", "relation-isolation"],
  "GET /api/tasks/:id": ["happy-path", "isolation", "unknown-id"],
  "PATCH /api/tasks/:id": ["happy-path", "isolation", "unknown-id", "invalid-input", "relation-isolation"],
  "DELETE /api/tasks/:id": ["happy-path", "isolation", "unknown-id"],
  "POST /api/tasks/:id/move": ["happy-path", "isolation", "unknown-id", "invalid-input", "relation-isolation"],
  "GET /api/tasks/:id/transitions": ["happy-path", "isolation", "unknown-id"],
  "GET /api/tasks/:id/runs": ["happy-path", "isolation", "unknown-id"],
  "GET /api/tasks/:id/page": ["happy-path", "isolation", "unknown-id"],
  "PUT /api/tasks/:id/page": ["happy-path", "isolation", "unknown-id", "invalid-input"],
  "POST /api/projects": ["happy-path", "invalid-input"],
  "GET /api/projects": ["happy-path", "isolation"],
  "GET /api/projects/:id": ["happy-path", "isolation", "unknown-id"],
  "PATCH /api/projects/:id": ["happy-path", "isolation", "unknown-id", "invalid-input", "relation-isolation"],
  "DELETE /api/projects/:id": ["happy-path", "isolation", "unknown-id"],
  "POST /api/people": ["happy-path", "invalid-input"],
  "GET /api/people": ["happy-path", "isolation"],
  "PATCH /api/people/:id": ["happy-path", "isolation", "unknown-id", "invalid-input"],
  "DELETE /api/people/:id": ["happy-path", "isolation", "unknown-id"],
  "POST /api/repos": ["happy-path", "invalid-input"],
  "GET /api/repos": ["happy-path", "isolation"],
  "PATCH /api/repos/:id": ["happy-path", "isolation", "unknown-id", "invalid-input"],
  "DELETE /api/repos/:id": ["happy-path", "isolation", "unknown-id"],
  "POST /api/deliverables": ["happy-path", "invalid-input", "relation-isolation"],
  "GET /api/deliverables": ["happy-path", "isolation"],
  "PATCH /api/deliverables/:id": ["happy-path", "isolation", "unknown-id", "invalid-input"],
  "DELETE /api/deliverables/:id": ["happy-path", "isolation", "unknown-id"],
  "POST /api/reminders": ["happy-path", "invalid-input"],
  "GET /api/reminders": ["happy-path", "isolation"],
  "POST /api/reminders/:id/dismiss": ["happy-path", "isolation", "unknown-id"],
  "DELETE /api/reminders/:id": ["happy-path", "isolation", "unknown-id"],
  "GET /api/calendar": ["happy-path", "invalid-input"],
  "GET /api/pages/:kind/:id/comments": ["happy-path", "isolation", "unknown-id", "invalid-input"],
  "POST /api/pages/:kind/:id/comments": ["happy-path", "isolation", "unknown-id", "invalid-input", "relation-isolation"],
  "PATCH /api/comments/:id": ["happy-path", "isolation", "unknown-id", "invalid-input"],
  "DELETE /api/comments/:id": ["happy-path", "isolation", "unknown-id"],
  "POST /api/pages/:kind/:id/ensemble": ["isolation", "unknown-id", "invalid-input", "relation-isolation", "hosted-verification"],
  "POST /api/pages": ["happy-path"],
  "POST /api/pages/:kind/:id/convert": ["happy-path", "isolation", "unknown-id", "invalid-input"],
  "GET /api/pages": ["happy-path", "isolation"],
  "GET /api/pages/:id": ["happy-path", "isolation", "unknown-id"],
  "PATCH /api/pages/:id": ["happy-path", "isolation", "unknown-id", "invalid-input"],
  "PUT /api/pages/:id": ["happy-path", "isolation", "unknown-id", "invalid-input"],
  "DELETE /api/pages/:id": ["happy-path", "isolation", "unknown-id"],
  "GET /api/runs": ["happy-path", "isolation", "invalid-input"],
  "GET /api/runs/:id": ["happy-path", "isolation", "unknown-id"],
  "DELETE /api/runs/:id": ["happy-path", "isolation", "unknown-id"],
  "GET /api/skills": ["happy-path", "isolation"],
  "POST /api/skills": ["happy-path", "invalid-input"],
  "PATCH /api/skills/:id": ["happy-path", "isolation", "unknown-id", "invalid-input"],
  "POST /api/skills/:id/restore": ["happy-path", "isolation", "unknown-id", "invalid-input"],
  "POST /api/skills/:id/score": ["happy-path", "isolation", "unknown-id", "invalid-input"],
  "DELETE /api/skills/:id": ["happy-path", "isolation", "unknown-id"],
  "GET /api/settings": ["happy-path", "isolation"],
  "PATCH /api/settings": ["happy-path", "isolation", "invalid-input"],
  "PUT /api/settings/modules": ["invalid-input"],
  "GET /api/preferences": ["happy-path", "isolation"],
  "PUT /api/preferences/:key": ["happy-path", "isolation", "invalid-input"],
  "POST /api/internal/ledger": ["happy-path", "invalid-input", "relation-isolation"],
  "POST /api/internal/runs/:id/steps": ["happy-path", "isolation", "unknown-id", "invalid-input"],
  "GET /api/documents": ["happy-path", "isolation"],
  "POST /api/documents": ["happy-path", "invalid-input", "relation-isolation"],
  "GET /api/documents/:id/text": ["happy-path", "isolation", "unknown-id"],
  "GET /api/documents/:id/original": ["happy-path", "isolation", "unknown-id"],
  "PATCH /api/documents/:id/tags": ["happy-path", "isolation", "unknown-id", "invalid-input", "relation-isolation"],
  "DELETE /api/documents/:id": ["happy-path", "isolation", "unknown-id"],
  "GET /api/diagrams": ["happy-path", "isolation"],
  "POST /api/diagrams": ["happy-path", "invalid-input"],
  "GET /api/diagrams/:id": ["happy-path", "isolation", "unknown-id"],
  "GET /api/diagrams/:id/svg": ["happy-path", "isolation", "unknown-id"],
  "PATCH /api/diagrams/:id": ["happy-path", "isolation", "unknown-id", "invalid-input"],
  "GET /api/diagrams/:id/revisions": ["happy-path", "isolation", "unknown-id"],
  "POST /api/diagrams/:id/restore": ["happy-path", "isolation", "unknown-id", "invalid-input"],
  "POST /api/diagrams/:id/duplicate": ["happy-path", "isolation", "unknown-id"],
  "DELETE /api/diagrams/:id": ["happy-path", "isolation", "unknown-id"],
  "GET /api/diagrams/links": ["happy-path", "isolation"],
  "PUT /api/diagrams/links": ["happy-path", "invalid-input", "relation-isolation"],
  "GET /api/plots": ["happy-path", "isolation"],
  "POST /api/plots": ["happy-path", "invalid-input", "relation-isolation"],
  "GET /api/plots/:id": ["happy-path", "isolation", "unknown-id"],
  "PATCH /api/plots/:id": ["happy-path", "isolation", "unknown-id", "invalid-input", "relation-isolation"],
  "POST /api/plots/:id/duplicate": ["happy-path", "isolation", "unknown-id"],
  "DELETE /api/plots/:id": ["happy-path", "isolation", "unknown-id"],
  "GET /api/plots/datasets": ["happy-path", "isolation"],
  "POST /api/plots/datasets": ["happy-path", "invalid-input"],
  "GET /api/plots/datasets/:id": ["happy-path", "isolation", "unknown-id"],
  "PATCH /api/plots/datasets/:id": ["happy-path", "isolation", "unknown-id", "invalid-input"],
  "DELETE /api/plots/datasets/:id": ["happy-path", "isolation", "unknown-id"],
  "GET /api/assistant/conversations": ["happy-path", "isolation"],
  "POST /api/assistant/conversations": ["happy-path", "invalid-input"],
  "GET /api/assistant/conversations/:id/messages": ["happy-path", "isolation", "unknown-id"],
  "POST /api/assistant/conversations/:id/stop": ["happy-path", "isolation", "unknown-id"],
  "GET /api/decisions": ["happy-path", "isolation", "invalid-input"],
  "POST /api/decisions": ["happy-path", "invalid-input"],
  "GET /api/decisions/:id/wait": ["happy-path", "isolation", "unknown-id", "invalid-input"],
  "POST /api/decisions/:id/cancel": ["happy-path", "isolation", "unknown-id"],
  "POST /api/decisions/:id/decide": ["happy-path", "isolation", "unknown-id", "invalid-input"],
  "GET /api/decision-rules": ["happy-path", "isolation"],
  "DELETE /api/decision-rules/:id": ["happy-path", "isolation", "unknown-id"],
  "GET /api/deleted": ["happy-path", "isolation"],
  "POST /api/deleted/restore": ["happy-path", "isolation", "invalid-input"],
  "GET /api/completed": ["happy-path", "isolation", "invalid-input"],
  "POST /api/tasks/:id/reopen": ["happy-path", "isolation", "unknown-id"],
  "POST /api/tasks/:id/pin": ["happy-path", "isolation", "unknown-id", "invalid-input"],
  "POST /api/deliverables/:id/reopen": ["happy-path", "isolation", "unknown-id"],
  "POST /api/deliverables/:id/pin": ["happy-path", "isolation", "unknown-id", "invalid-input"],
  "GET /api/approvals": ["happy-path", "isolation"],
  "POST /api/approvals/:id/decide": ["happy-path", "isolation", "unknown-id", "invalid-input"],
  "GET /api/notifications": ["happy-path", "isolation"],
  "POST /api/notifications/:id/read": ["happy-path", "isolation", "unknown-id"],
  "POST /api/notifications/read": ["happy-path", "isolation"],
  "GET /api/meetings/sessions": ["happy-path", "isolation"],
  "POST /api/meetings/sessions": ["happy-path", "invalid-input", "relation-isolation"],
  "GET /api/meetings/sessions/:id": ["happy-path", "isolation", "unknown-id"],
  "PATCH /api/meetings/sessions/:id": ["happy-path", "isolation", "unknown-id", "invalid-input"],
  "POST /api/meetings/sessions/:id/end": ["happy-path", "isolation", "unknown-id"],
  "POST /api/meetings/sessions/:id/decline": ["happy-path", "isolation", "unknown-id"],
  "POST /api/meetings/sessions/:id/recap": ["happy-path", "isolation", "unknown-id"],
  "DELETE /api/meetings/sessions/:id": ["happy-path", "isolation", "unknown-id"],
  "GET /api/layouts/:surface": ["happy-path", "isolation", "invalid-input"],
  "PUT /api/layouts/:surface": ["happy-path", "isolation", "invalid-input", "relation-isolation"],
  "POST /api/layouts/:surface/reset": ["happy-path", "isolation"],
  "POST /api/devices/pair": ["happy-path"],
  "POST /api/devices/register": ["happy-path", "invalid-input"],
  "GET /api/devices": ["happy-path", "isolation"],
  "DELETE /api/devices/:id": ["happy-path", "isolation", "unknown-id"],
  "POST /api/devices/self/heartbeat": ["happy-path", "invalid-input"],
  "POST /api/devices/self/claim": ["happy-path"],
  "POST /api/devices/self/jobs/:id/progress": ["happy-path", "isolation", "unknown-id", "invalid-input"],
  "POST /api/assistant/apply": ["happy-path", "isolation", "invalid-input", "relation-isolation"],
  "GET /api/ensemble/replies": ["happy-path", "isolation", "invalid-input"],
  "POST /api/ensemble/replies/:id/applied": ["happy-path", "isolation", "unknown-id", "invalid-input"],
  "GET /api/watchers": ["happy-path", "isolation"],
  "POST /api/watchers/:id/cancel": ["happy-path", "isolation", "unknown-id"],
  "GET /api/shell": ["happy-path", "isolation"],
  "DELETE /api/preferences/:key": ["happy-path", "isolation"],
  "POST /api/assistant/turn": ["invalid-input", "hosted-verification"],
  "POST /api/ensemble/invoke": ["hosted-verification"],
};

/** Connector store, provider OAuth and workspace connections. Owned by src/routes/connectors.ts. */
export const connectorRouteCoverage: Readonly<Record<string, readonly RouteCheck[]>> = {
  "GET /api/connectors/catalog": ["happy-path", "isolation"],
  "GET /api/connectors/apps": ["happy-path"],
  "PUT /api/connectors/apps/:provider": ["invalid-input", "hosted-verification"],
  "GET /api/connectors/google/picker": ["happy-path", "invalid-input"],
  "GET /api/connectors/:provider/start": ["happy-path", "invalid-input", "hosted-verification"],
  "GET /api/connectors/:provider/callback": ["happy-path", "isolation", "invalid-input", "hosted-verification"],
  "PUT /api/connectors/:id/products": ["happy-path", "isolation", "unknown-id", "invalid-input"],
  "POST /api/connectors/:provider/token": ["happy-path", "invalid-input", "hosted-verification"],
  "DELETE /api/connectors/:provider": ["happy-path", "isolation", "invalid-input"],
};

/** Remote MCP connections. Owned by src/routes/mcp-connections.ts. */
export const mcpConnectionRouteCoverage: Readonly<Record<string, readonly RouteCheck[]>> = {
  "GET /api/mcp-connections": ["happy-path", "isolation", "hosted-verification"],
  "POST /api/mcp-connections": ["happy-path", "invalid-input", "hosted-verification"],
  "GET /api/mcp-connections/callback": ["happy-path", "invalid-input"],
  "POST /api/mcp-connections/:id/refresh-tools": ["happy-path", "isolation", "unknown-id"],
  "PATCH /api/mcp-connections/:id": ["happy-path", "isolation", "unknown-id", "invalid-input"],
  "DELETE /api/mcp-connections/:id": ["happy-path", "isolation", "unknown-id"],
  "GET /api/mcp-client-metadata.json": ["happy-path"],
};

/** Imports from other apps. Owned by src/routes/imports.ts. */
export const importRouteCoverage: Readonly<Record<string, readonly RouteCheck[]>> = {
  "GET /api/imports/sources": ["happy-path"],
  "POST /api/imports/preview": ["happy-path", "isolation", "invalid-input", "hosted-verification"],
  "POST /api/imports": ["happy-path", "isolation", "invalid-input", "hosted-verification"],
  "GET /api/imports": ["happy-path", "isolation"],
  "GET /api/imports/:id": ["happy-path", "isolation", "unknown-id"],
  "POST /api/imports/:id/cancel": ["happy-path", "isolation", "unknown-id"],
  "POST /api/imports/:id/undo": ["happy-path", "isolation", "unknown-id", "invalid-input"],
};

/** People identities, project links and imported meeting notes. Owned by routes/people-identity.ts, project-links.ts, meeting-notes.ts. */
export const connectedDataRouteCoverage: Readonly<Record<string, readonly RouteCheck[]>> = {
  "GET /api/people/identity-suggestions": ["happy-path", "isolation"],
  "POST /api/people/identity-suggestions/dismiss": ["happy-path", "isolation", "invalid-input"],
  "POST /api/people/:id/merge": ["happy-path", "isolation", "unknown-id", "invalid-input"],
  "GET /api/project-links": ["happy-path", "isolation"],
  "POST /api/project-links": ["happy-path", "invalid-input", "relation-isolation"],
  "DELETE /api/project-links/:id": ["happy-path", "isolation", "unknown-id"],
  "GET /api/project-links/containers": ["happy-path", "isolation", "invalid-input"],
  "GET /api/meetings/imported": ["happy-path", "isolation"],
  "GET /api/meetings/notes/:id": ["happy-path", "isolation", "unknown-id"],
};

/** Ensemble spaces. Owned by src/spaces/routes.ts; checked in src/spaces/spaces.integration.test.ts. */
export const spacesRouteCoverage: Readonly<Record<string, readonly RouteCheck[]>> = {
  "GET /api/spaces": ["happy-path", "isolation"],
  "POST /api/spaces": ["happy-path", "invalid-input"],
  "POST /api/spaces/:id/switch": ["isolation"],
  "PATCH /api/spaces/:id": ["isolation"],
  "DELETE /api/spaces/:id": ["happy-path", "isolation", "invalid-input"],
  "POST /api/spaces/settings/copy": ["happy-path", "isolation"],
  "PUT /api/spaces/settings/sync": ["happy-path"],
};

/** Sharing and presence. Owned by src/sharing/routes.ts; checked in src/sharing/sharing.integration.test.ts. */
export const sharingRouteCoverage: Readonly<Record<string, readonly RouteCheck[]>> = {
  "GET /api/sharing/people": ["happy-path", "invalid-input"],
  "GET /api/sharing/overview": ["happy-path"],
  "GET /api/sharing/contacts": ["happy-path"],
  "POST /api/sharing/contacts": ["happy-path", "invalid-input"],
  "DELETE /api/sharing/contacts/:id": ["happy-path", "isolation"],
  "GET /api/sharing/with-me": ["happy-path"],
  "GET /api/sharing/spaces/:id/members": ["happy-path", "isolation"],
  "POST /api/sharing/spaces/:id/members": ["happy-path", "isolation", "invalid-input"],
  "PATCH /api/sharing/spaces/:id/members/:personId": ["happy-path"],
  "DELETE /api/sharing/spaces/:id/members/:personId": ["happy-path", "isolation"],
  "POST /api/sharing/spaces/:id/transfer": ["happy-path", "isolation", "invalid-input"],
  "GET /api/sharing/items": ["happy-path", "isolation"],
  "POST /api/sharing/items": ["happy-path", "invalid-input"],
  "PATCH /api/sharing/items/:id": ["happy-path", "isolation"],
  "DELETE /api/sharing/items/:id": ["happy-path"],
  "GET /api/sharing/open/:id": ["happy-path", "isolation"],
  "GET /api/presence": ["happy-path", "isolation"],
  "POST /api/presence": ["happy-path"],
};

export const routeCoverage = {
  ...resourceRouteCoverage,
  ...authRouteCoverage,
  ...cliAuthRouteCoverage,
  ...mcpRouteCoverage,
  ...connectorRouteCoverage,
  ...mcpConnectionRouteCoverage,
  ...importRouteCoverage,
  ...connectedDataRouteCoverage,
  ...spacesRouteCoverage,
  ...sharingRouteCoverage,
};
